---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: no  # Disable gathering facts for localhost

  tasks:    

    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        instance_type: t2.micro
        image_id: ami-05c13eab67c5d8861
        key_name: keyforDestop
        region: us-east-1
        security_group: launch-wizard-5
        count: "{{nmachines}}"
        tags:
          Name: "{{nameofec2}}"
      register: ec2

    - name: Set up the the ec2s tabs
      ansible.builtin.lineinfile:
        path: /mnt/c/Users/kochf/Downloads/myscripts/awsinvent.aws_ec2.yaml
        regexp: '^\s+tag:Name:'
        line: '  tag:Name: "{{nameofec2}}"'


      # ansible.builtin.replace:
      #   path: /mnt/c/Users/kochf/Downloads/myscripts/awsinvent.aws_ec2.yaml
      #   after: 'filters:'
      #   regexp: 'Tomcat'
      #   replace: '{{nameofec2}}'

    
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ item.network_interfaces[0].association.public_ip }}"
        port: 22
        state: started 
      loop: "{{ec2.instances}}"  

    
    - name: example ec2 group
      amazon.aws.ec2_security_group:
        name: launch-wizard-5
        description: launch-wizard-5 created 2023-06-11T09:29:24.949Z
        purge_rules: false
        rules:
          - proto: tcp
            from_port: "{{userport}}"
            to_port: "{{userport}}"
            cidr_ip: 0.0.0.0/0
